### ISSUE TITLE
多用户怎么设置呢？

### ISSUE THREAD

**Issue by 493Arceus** [NeverBehave/BilibiliHelper#1]
config文件只知道配置单用户的格式，多用户应该怎么配置呢？

**Comment by NeverBehave** [comment]
@493Arceus tools下面有帮助你批量生成配置文件的工具，默认输出到config/，multiple在运行的时候会搜索该目录并全部载入

**Comment by 493Arceus** [comment]
emmmm好的，那麻烦改一下README.md里的仓库地址……clone的仓库都是单用户的
